### ISSUE TITLE
Cannot create more than 3 groups

### ISSUE THREAD

**Issue by artfwo** [wrl/rove#1]
I have a 8x8 arduinome and I'd like to have 4 groups in my session. Neither of these would work. Rove automatically trims the number of groups to 3. All the "files" tagged as group=4 just go into group3 - pressing the button in such a row stops other tracks in group3 and pressing 3rd button in the top row mutes them.

I also tried to increase number of groups to 5. Didn't have any effect. Here's my session file:

[session]
bpm      = 74
quantize = .25 # fraction of a quarter note to quantize to
groups   = 4
pattern1 = 8
pattern2 = 8

[file]
path = session/drums1.wav
group = 1

[file]
path = session/drums2.wav
group = 1

[file]
path = session/melody1.wav
group = 2

[file]
path = session/melody2.wav
group = 3

[file]
path = session/piano.wav
group = 4

[file]
path = session/pluck.wav
group = 4

**Comment by artfwo** [comment]
The bug occurs due to state.group_count initialized twice in session.c (198) and rove.c (211)

**Comment by wrl** [comment]
it looks like the issue is the one in rove.c. i'll test a fix and then push it up.

**Comment by artfwo** [comment]
if it helps, I've tested rove after commenting out the line "state.group_count = state.config.cols - 5;" everything worked beautifully. great app btw!

**Comment by artfwo** [comment]
thanks for the fix!
